apiVersion: apps/v1
kind: Deployment
metadata:
  name: conferences-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conferences
  template:
    metadata:
      labels:
        app: conferences
    spec:
      containers:
        - name: conferences
          image: madersky/conferences
          env:
            - name: NATS_URL
              value: "https://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: conviera
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGO_URI
              value: "mongodb://conferences-mongo-srv:27017/conferences"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: conferences-srv
spec:
  selector:
    app: conferences
  ports:
    - name: conferences
      protocol: TCP
      port: 3000
      targetPort: 3000
