apiVersion: apps/v1
kind: Deployment
metadata:
  name: speeches-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speeches
  template:
    metadata:
      labels:
        app: speeches
    spec:
      containers:
        - name: speeches
          image: madersky/speeches
          env:
            - name: NATS_URL
              value: "https://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: conviera
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGO_URI
              value: "mongodb://speeches-mongo-srv:27017/speeches"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: speeches-srv
spec:
  selector:
    app: speeches
  ports:
    - name: speeches
      protocol: TCP
      port: 3000
      targetPort: 3000
